namespace Scenario01.DocumentProcessing.Models;

/// <summary>
/// Aggregated report summarizing document processing activity for a given date.
/// Generated by the daily reporting function.
/// </summary>
/// <param name="ReportDate">The date this report covers.</param>
/// <param name="TotalProcessed">The total number of documents processed.</param>
/// <param name="SuccessCount">The number of documents processed successfully.</param>
/// <param name="FailureCount">The number of documents that failed processing.</param>
/// <param name="AverageProcessingTimeMs">The average processing time in milliseconds.</param>
/// <param name="ClassificationBreakdown">A breakdown of document counts by classification type.</param>
public record ProcessingReport(
    DateTimeOffset ReportDate,
    int TotalProcessed,
    int SuccessCount,
    int FailureCount,
    double AverageProcessingTimeMs,
    Dictionary<string, int> ClassificationBreakdown);
